export const LOGIN_SELL_REQUEST = "LOGIN_SELL_REQUEST";
export const LOGIN_SELL_SUCCESS = "LOGIN_SELL_SUCCESS";
export const LOGIN_SELL_FAIL = "LOGIN_SELL_FAIL";

export const REGISTER_SELL_REQUEST = "REGISTER_SELL_REQUEST";
export const REGISTER_SELL_SUCCESS = "REGISTER_SELL_SUCCESS";
export const REGISTER_SELL_FAIL = "REGISTER_SELL_FAIL";

export const LOAD_SELL_REQUEST = "LOAD_SELL_REQUEST";
export const LOAD_SELL_SUCCESS = "LOAD_SELL_SUCCESS";
export const LOAD_SELL_FAIL = "LOAD_SELL_FAIL";

export const LOGOUT_SELL_SUCCESS = "LOGOUT_SELL_SUCCESS";
export const LOGOUT_SELL_FAIL = "LOGOUT_SELL_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ALL_SELL_REQUEST = "ALL_SELL_REQUEST";
export const ALL_SELL_SUCCESS = "ALL_SELL_SUCCESS";
export const ALL_SELL_FAIL = "ALL_SELL_FAIL";

export const SELL_DETAILS_REQUEST = "SELL_DETAILS_REQUEST";
export const SELL_DETAILS_SUCCESS = "SELL_DETAILS_SUCCESS";
export const SELL_DETAILS_FAIL = "SELL_DETAILS_FAIL";

export const UPDATE_SELL_REQUEST = "UPDATE_SELL_REQUEST";
export const UPDATE_SELL_SUCCESS = "UPDATE_SELL_SUCCESS";
export const UPDATE_SELL_RESET = "UPDATE_SELL_RESET";
export const UPDATE_SELL_FAIL = "UPDATE_SELL_FAIL";

export const DELETE_SELL_REQUEST = "DELETE_SELL_REQUEST";
export const DELETE_SELL_SUCCESS = "DELETE_SELL_SUCCESS";
export const DELETE_SELL_RESET = "DELETE_SELL_RESET";
export const DELETE_SELL_FAIL = "DELETE_SELL_FAIL";

export const REMOVE_SELL_DETAILS = "REMOVE_SELL_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";